import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createHash, createHmac, randomUUID } from 'node:crypto';
import vm from 'node:vm';
import { FIELD_NAMES, HEADERS, validateSubmission } from '../src/validation.mjs';
import { personnelForm } from '../src/form-definition.mjs';
import { handleRequest, signEnvelope } from '../src/worker.mjs';
const read = path => readFileSync(new URL('../' + path, import.meta.url), 'utf8');
const data = () => ({ firstName: 'Test', middleName: 'Example', lastName: 'Person', designation: 'Technical Staff', office: 'Program Development Unit', email: 'TEST@example.invalid', contactNumber: '09999999999', shirtSize: 'M' });
const SECRET = 'a'.repeat(64); // Isolated fixture; never configure production with this value.
function receiver() {
  const rows = [[...HEADERS]];
  let writes = 0;
  let locked = false;
  const context = vm.createContext({
    PropertiesService: { getScriptProperties: () => ({ getProperties: () => ({ SPREADSHEET_ID: 'fixture', SHEET_NAME: 'Sheet1', RELAY_SECRET: SECRET }) }) },
    SpreadsheetApp: { openById: () => ({ getSheetByName: () => ({ getLastRow: () => rows.length, getMaxRows: () => 1000,
      getRange: (r,c,n,w) => ({ getDisplayValues: () => rows.slice(r-1,r-1+n).map(row => row.slice(c-1,c-1+w)) }) }) }) },
    LockService: { getScriptLock: () => ({ tryLock: () => { locked=true; return true; }, releaseLock: () => { locked=false; } }) },
    Utilities: { Charset: { UTF_8:'UTF-8' }, DigestAlgorithm: { SHA_256:'sha256' },
      computeDigest: (_,s) => [...createHash('sha256').update(s).digest()],
      computeHmacSha256Signature: (s,k) => [...createHmac('sha256',k).update(s).digest()],
      formatDate: () => '2026-09-11T12:00:00' },
    ContentService: { MimeType: { JSON:'application/json' }, createTextOutput: text => ({ text, setMimeType() { return this; } }) },
    Sheets: { Spreadsheets: { Values: {
      update(value,id,range,options) { assert.equal(locked,true); assert.equal(options.valueInputOption,'RAW'); rows[Number(range.match(/!A(\d+)/)[1])-1]=value.values[0]; writes++; return { updatedRows:1 }; },
      get(id,range) { return { values:[rows[Number(range.match(/!A(\d+)/)[1])-1]] }; }
    } } }
  });
  vm.runInContext(read('apps-script/Code.gs'),context);
  return { rows, count:()=>writes, post: envelope => JSON.parse(context.doPost({postData:{type:'application/json',contents:JSON.stringify(envelope)}}).text) };
}
for (const name of FIELD_NAMES) test('release: ' + name + ' is required in model, HTML and receiver', async () => {
  assert.equal(personnelForm.getFields().find(f=>f.id===name).data.required,true);
  assert.match(read('dist/index.html'),new RegExp('<(?:input|select)\\b[^>]*id="'+name+'"[^>]*\\brequired\\b'));
  const gas=receiver();
  for (const value of [undefined,null,'','   ','\u00a0']) {
    const bad={...data(),[name]:value};
    assert.equal(validateSubmission(bad).ok,false);
    assert.equal(gas.post(await signEnvelope(bad,randomUUID(),SECRET)).ok,false);
  }
  assert.equal(gas.count(),0);
});
test('release: normalized phone values retain national/international prefix',()=>{
  assert.equal(validateSubmission({...data(),contactNumber:'0917 123-4567'}).data.contactNumber,'09171234567');
  assert.equal(validateSubmission({...data(),contactNumber:'(+63) 917 123 4567'}).data.contactNumber,'+639171234567');
  assert.equal(validateSubmission({...data(),contactNumber:'+14155551234'}).ok,false);
});
test('release: signed save, unchanged retry and new duplicate remain distinct',async()=>{
  const gas=receiver(), id=randomUUID();
  const first=gas.post(await signEnvelope(data(),id,SECRET));
  assert.equal(first.ok,true);
  assert.deepEqual(gas.post(await signEnvelope(data(),id,SECRET)),first);
  assert.equal(gas.count(),1);
  const next=gas.post(await signEnvelope({...data(),email:'test@example.invalid'},randomUUID(),SECRET));
  assert.equal(next.ok,true); assert.equal(gas.count(),2);
  assert.equal(gas.rows[2][10],'Needs review'); assert.equal(gas.rows[2][11],first.submissionId);
});
test('release: generated backend matches shared validation and backend sources',()=>{
  assert.equal(read('apps-script/Code.gs'),'// GENERATED by npm run build. Paste this COMPLETE file into Apps Script.\n'+read('src/validation.mjs').replace(/^export /gm,'')+'\n'+read('apps-script/Backend.gs'));
});
test('release: public HTML has four matching fragment targets and one current link',()=>{
  const html=read('dist/index.html');
  assert.match(html,/<nav\b[^>]*aria-labelledby="on-this-page"/);
  assert.match(html,/<h2 id="on-this-page">On this page<\/h2>/);
  const nav=html.match(/<nav\b[\s\S]*?<\/nav>/)[0];
  assert.equal((nav.match(/aria-current="location"/g)||[]).length,1);
  const hashes=[...nav.matchAll(/href="#([^"]+)"/g)].map(m=>m[1]);
  assert.equal(hashes.length,4);
  for (const id of hashes) assert.match(html,new RegExp('<fieldset id="'+id+'" data-scroll-section'));
  assert.match(html,/<script type="module" src="\/scrollspy.mjs">/);
});
test('release: observer, dynamic offsets, strong indicator and reduced motion included',()=>{
  const js=read('dist/scrollspy.mjs'), css=read('dist/styles.css');
  assert.match(js,/new IntersectionObserver/); assert.match(js,/rootMargin:/);
  assert.match(js,/new ResizeObserver/); assert.match(js,/observer\.observe\(target\)/);
  assert.match(css,/\.page-rail\s*\{[^}]*position:\s*sticky/);
  assert.match(css,/a\[aria-current="location"\]::before\s*\{\s*background:\s*var\(--ink\)/);
  assert.match(css,/prefers-reduced-motion/); assert.doesNotMatch(css,/gradient\(/);
  const hues=[...css.matchAll(/hsl\((\d+)/g)].map(m=>m[1]);
  assert.ok(hues.length>0); assert.deepEqual([...new Set(hues)],['215']);
});
test('release: no optional respondent label; honeypot stays empty and not required',()=>{
  const html=read('dist/index.html'); assert.doesNotMatch(html,/\(optional\)/);
  const honey=html.match(/<input\b[^>]*id="website"[^>]*>/)[0]; assert.doesNotMatch(honey,/\brequired\b/);
});
test('release: unconfigured Worker cannot accept a submission',async()=>{
  const req=new Request('https://test.invalid/api/submit',{method:'POST',body:'{}'});
  const response=await handleRequest(req,{}); assert.equal(response.status,503);
});
