import { readFile, writeFile, mkdir, cp, rm } from 'node:fs/promises';
import { personnelForm } from '../src/form-definition.mjs';
const root = new URL('../', import.meta.url);
const path = name => new URL(name, root);
const escape = value => String(value).replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' })[char]);
function render(field) {
  const { name, label, required, type } = field.data;
  const hint = name === 'contactNumber' ? 'Use 09XXXXXXXXX or +639XXXXXXXXX. Spaces and hyphens are accepted.' : '';
  const attrs = `id="${name}" name="${name}" ${required ? 'required' : ''} aria-describedby="${name}-error${hint ? ' ' + name + '-hint' : ''}"`;
  let control;
  if (type === 'select') {
    control = `<select ${attrs}><option value="">Select ${name === 'shirtSize' ? 'a size' : 'an option'}</option>${field.getChoices().map(c => `<option value="${escape(c.id)}">${escape(c.data.label)}</option>`).join('')}</select>`;
  } else {
    const inputType = field.ui.inputType;
    control = `<input ${attrs} type="${inputType}" maxlength="${field.properties.maxLength}" autocomplete="${field.ui.autocomplete}"${inputType === 'tel' ? ' inputmode="tel" placeholder="09XXXXXXXXX"' : ''}${inputType === 'email' ? ' spellcheck="false" autocapitalize="none"' : ''}>`;
  }
  return `<div class="field"><label for="${name}">${escape(label)} ${required ? '<span class="required" aria-hidden="true">*</span>' : '<span class="optional">(optional)</span>'}</label>${control}${hint ? `<p id="${name}-hint" class="helper">${hint}</p>` : ''}<p class="field-error" id="${name}-error" hidden></p></div>`;
}
await rm(path('dist/'), { recursive: true, force: true }); await mkdir(path('dist/assets/'), { recursive: true });
let html = await readFile(path('web/index.html'), 'utf8');
for (const section of ['personal', 'appointment', 'contact', 'shirt']) {
  html = html.replace('{{' + section + '}}', personnelForm.getFields().filter(f => f.ui.section === section).map(render).join('\n'));
}
if (/{{\w+}}/.test(html)) throw new Error('Unresolved template field');
await writeFile(path('dist/index.html'), html);
await cp(path('web/styles.css'), path('dist/styles.css'));
await cp(path('src/app.mjs'), path('dist/app.mjs'));
await cp(path('src/scrollspy.mjs'), path('dist/scrollspy.mjs'));
await cp(path('src/validation.mjs'), path('dist/validation.mjs'));
await cp(path('assets/shirt-size-guide.webp'), path('dist/assets/shirt-size-guide.webp'));
const validation = (await readFile(path('src/validation.mjs'), 'utf8')).replace(/^export /gm, '');
const backend = await readFile(path('apps-script/Backend.gs'), 'utf8');
await writeFile(path('apps-script/Code.gs'), '// GENERATED by npm run build. Paste this COMPLETE file into Apps Script.\n' + validation + '\n' + backend);
console.log('Built dist/ and apps-script/Code.gs. No credentials or submission data included.');
